version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: authorio-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: authorio

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: authorio-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://mongodb:27017/authorio
      JWT_SECRET: ${JWT_SECRET}
      CLIENT_URL: ${CLIENT_URL:-http://localhost:3000}
    env_file:
      - server/.env

volumes:
  mongodb_data:


